version: '3.8'
services:
  flask-app:
    image: "${DOCKER_USERNAME}/myapp:${APP1_IMAGE_TAG:-latest}"
    container_name: flask-app
    ports:
      - "8001:80"
    environment:
      - INSTANCE_NAME=flask-app
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge